In [ ]:
import numpy as np
import tensorflow as tf
import torch
from datasets import Dataset

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
np_arr

In [11]:
np_rec = np.rec.array([(1, 2.5, 'a'), (3, 4.5, 'b')], dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'U1')])
np_rec

rec.array([(1, 2.5, 'a'), (3, 4.5, 'b')],
          dtype=[('x', '<i4'), ('y', '<f4'), ('z', '<U1')])

In [12]:
tf_tensor = tf.constant([[1, 2], [3, 4]])
tf_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
tf_var = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
tf_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [14]:
tf_sparse = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
tf_sparse

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

In [15]:
torch_tensor = torch.tensor([[1, 2], [3, 4]])
torch_tensor

tensor([[1, 2],
        [3, 4]])

In [16]:
hf_data = {"name": ["Alice", "Bob", "Charlie"], "age": [25, 30, 35]}
hf_dataset = Dataset.from_dict(hf_data)
hf_dataset

Dataset({
    features: ['name', 'age'],
    num_rows: 3
})