In [1]:
# 5. Linear Algebra — matrix operations with numpy
import numpy as np

A = np.array([[3, 1, 2], [2, 4, 1], [1, 2, 5]])
B = np.array([[1, 0, 1], [0, 2, 1], [1, 1, 0]])

print('A =\n', A)
print('B =\n', B)
print('A @ B =\n', A @ B)
print('det(A) =', round(np.linalg.det(A), 6))
print('A^-1 =\n', np.round(np.linalg.inv(A), 4))
vals, vecs = np.linalg.eig(A)
print('Eigenvalues of A:', np.round(vals, 4))


A =
 [[3 1 2]
 [2 4 1]
 [1 2 5]]
B =
 [[1 0 1]
 [0 2 1]
 [1 1 0]]
A @ B =
 [[5 4 4]
 [3 9 6]
 [6 9 3]]
det(A) = 45.0
A^-1 =
 [[ 0.4    -0.0222 -0.1556]
 [-0.2     0.2889  0.0222]
 [ 0.     -0.1111  0.2222]]
Eigenvalues of A: [7.1409+0.j     2.4295+0.6317j 2.4295-0.6317j]


In [2]:
# 4. Statistics with numpy
import numpy as np

np.random.seed(42)
data = np.random.normal(loc=50, scale=10, size=1000)

print(f'Mean:     {np.mean(data):.4f}')
print(f'Median:   {np.median(data):.4f}')
print(f'Std dev:  {np.std(data):.4f}')
print(f'Variance: {np.var(data):.4f}')
print(f'Min/Max:  {data.min():.4f} / {data.max():.4f}')
print(f'25th pct: {np.percentile(data, 25):.4f}')
print(f'75th pct: {np.percentile(data, 75):.4f}')

Mean:     50.1933
Median:   50.2530
Std dev:  9.7873
Variance: 95.7905
Min/Max:  17.5873 / 88.5273
25th pct: 43.5241
75th pct: 56.4794


In [4]:
# 3. Calculus — derivatives & integrals with sympy
from sympy import symbols, diff, integrate, sin, cos, exp, pi, oo

x = symbols('x')

f = x**3 * sin(x)
print('f(x)  =', f)
print("f'(x) =", diff(f, x))
print("f''(x)=", diff(f, x, 2))

print('∫ x^3 dx =', integrate(x**3, x))
print('∫₀^π sin(x) dx =', integrate(sin(x), (x, 0, pi)))
print('∫₀^∞ e^-x dx =', integrate(exp(-x), (x, 0, oo)))

NameError: name 'symbols' is not defined

In [ ]:
# 2. Algebra — solving equations with sympy
from sympy import symbols, solve, expand, factor

x, y = symbols('x y')

eq1 = x**2 - 5*x + 6
print('Roots of x^2 - 5x + 6:', solve(eq1, x))

system = [2*x + y - 5, x - 3*y + 1]
print('System solution:', solve(system, [x, y]))

expr = (x + 2)**3
print('Expand (x+2)^3:', expand(expr))
print('Factor x^3+6x^2+12x+8:', factor(expr))

In [ ]:
# 1. Arithmetic & Number Theory
import math

print('Factorials:', [math.factorial(n) for n in range(1, 8)])
print('GCD(48, 18):', math.gcd(48, 18))
print('LCM(12, 18):', math.lcm(12, 18))
print('Primes check:', [(n, all(n % i != 0 for i in range(2, int(n**0.5)+1))) for n in range(2, 20) if all(n % i != 0 for i in range(2, int(n**0.5)+1))])